print("############################## \n")
print("#                            # \n")
print("#     Salma Nur Lathifah     # \n")
print("#        2510817120013       # \n")
print("#                            # \n")
print("##############################")